create table people(
                       id int primary key generated by default as identity,
                       name varchar(255) not null,
                       age int8 not null,
                       email varchar(255) not null,
                       updated_at timestamp not null,
                       created_at timestamp not null,
                       created_who varchar(255) not null
)